# coding: utf8
import os

file = "ESHSmicrodat"

def sum_found(found):
    cpt = 0
    for f in found:
        if f:
            cpt += 1
    return cpt

with open(file) as f:
    rows = [row.replace('\n',"") for row in f.readlines()]

data_structure = [
    {'att_name': 'CCAA', 'att_pos': [1, 2], 'att_desc': 'Comunidad Autónoma'},
    {'att_name': 'SEXO', 'att_pos': [3, 3], 'att_desc': 'Sexo'},
    {'att_name': 'A_2A', 'att_pos': [4, 5], 'att_desc': 'Mes de nacimiento'},
    {'att_name': 'A_2B', 'att_pos': [6, 9], 'att_desc': 'Año de nacimiento'},
    {'att_name': 'EDAD', 'att_pos': [10, 12], 'att_desc': 'Edad'},
    {'att_name': 'A_3A', 'att_pos': [13, 13], 'att_desc': 'Nacido en España o no'},
    {'att_name': 'A_3B', 'att_pos': [14, 15], 'att_desc': 'Si es en España, indicar CCAA'},
    {'att_name': 'A_3C', 'att_pos': [16, 17], 'att_desc': 'País de nacimiento, si no es nacido en España'},
    {'att_name': 'A_4A', 'att_pos': [18, 18], 'att_desc': 'Nivel de estudios'},
    {'att_name': 'A_4B', 'att_pos': [19, 19], 'att_desc': 'Nivel de estudios del padre'},
    {'att_name': 'A_4C', 'att_pos': [20, 20], 'att_desc': 'Nivel de estudios de la madre'},
    {'att_name': 'A_5', 'att_pos': [21, 22], 'att_desc': 'Actividad económica (últimos 12 meses)'},
    {'att_name': 'A_6_1', 'att_pos': [23, 23], 'att_desc': 'Actividad económica (semana pasada):Trabajando'},
    {'att_name': 'A_6_2', 'att_pos': [24, 24], 'att_desc': 'Actividad económica (semana pasada):Con empleo pero temporalmente ausente'},
    {'att_name': 'A_6_3', 'att_pos': [25, 25], 'att_desc': 'Actividad económica (semana pasada):Parado/a que ha trabajado antes'},
    {'att_name': 'A_6_4', 'att_pos': [26, 26], 'att_desc': 'Actividad económica (semana pasada):Parado/a que busca su primer empleo'},
    {'att_name': 'A_6_5', 'att_pos': [27, 27], 'att_desc': 'Actividad económica (semana pasada):Incapacitado/a  para trabajar'},
    {'att_name': 'A_6_6', 'att_pos': [28, 28], 'att_desc': 'Actividad económica (semana pasada):Pensionista'},
    {'att_name': 'A_6_7', 'att_pos': [29, 29], 'att_desc': 'Actividad económica (semana pasada):Cursando algún estudio'},
    {'att_name': 'A_6_8', 'att_pos': [30, 30], 'att_desc': 'Actividad económica (semana pasada):Dedicado/a principalmente a las labores del hogar (actividad no económica )'},
    {'att_name': 'A_6_9', 'att_pos': [31, 31], 'att_desc': 'Actividad económica (semana pasada):Dedicado/a al voluntariado (ONG, parroquias etc.)'},
    {'att_name': 'A_6_10', 'att_pos': [32, 32], 'att_desc': 'Actividad económica (semana pasada):Otra situación sin ejercer actividad económica alguna (rentistas, recibiendo alguna ayuda pública o privada, etc.)'},
    {'att_name': 'A_6_11', 'att_pos': [33, 33], 'att_desc': 'Actividad económica (semana pasada):No consta'},
    {'att_name': 'A_7', 'att_pos': [34, 34], 'att_desc': 'Trabajo alguna vez en la vida'},
    {'att_name': 'A_8', 'att_pos': [35, 36], 'att_desc': 'Ocupación'},
    {'att_name': 'A_9', 'att_pos': [37, 37], 'att_desc': 'Situación profesional'},
    {'att_name': 'A_10', 'att_pos': [38, 38], 'att_desc': 'Estado civil'},
    {'att_name': 'B_11', 'att_pos': [39, 39], 'att_desc': 'Vive sólo o con otras personas'},
    {'att_name': 'B_12A', 'att_pos': [40, 40], 'att_desc': 'Convivencia con: Cónyuge/Pareja'},
    {'att_name': 'B_12B', 'att_pos': [41, 41], 'att_desc': 'Convivencia con: Padre/madre/tutor'},
    {'att_name': 'B_12C', 'att_pos': [42, 42], 'att_desc': 'Convivencia con: Hijos propios'},
    {'att_name': 'B_12D', 'att_pos': [43, 43], 'att_desc': 'Convivencia con: Hijos de la pareja/cónyuge'},
    {'att_name': 'B_12E', 'att_pos': [44, 44], 'att_desc': 'Convivencia con: Otros familiares carnales o politicos'},
    {'att_name': 'B_12F', 'att_pos': [45, 45], 'att_desc': 'Convivencia con: Amigos/Compañeros de piso'},
    {'att_name': 'B_12G', 'att_pos': [46, 46], 'att_desc': 'Convivencia con: Otras personas'},
    {'att_name': 'B_12H', 'att_pos': [47, 47], 'att_desc': 'Convivencia con: No consta'},
    {'att_name': 'B_13', 'att_pos': [48, 48], 'att_desc': 'Frecuencia de salidas nocturnas'},
    {'att_name': 'B_14', 'att_pos': [49, 49], 'att_desc': 'Frecuencia con la que pasa la noche fuera de casa por razones de trabajo o estudios'},
    {'att_name': 'B_15', 'att_pos': [50, 50], 'att_desc': 'Consumo de bebidas alcoholicas'},
    {'att_name': 'B_16', 'att_pos': [51, 51], 'att_desc': 'Frecuencia de consumo de alcohol'},
    {'att_name': 'B_17', 'att_pos': [52, 52], 'att_desc': 'Número de copas/cañas de alcohol habituales al día'},
    {'att_name': 'B_18', 'att_pos': [53, 54], 'att_desc': 'Días que ha estado bebido en el último mes'},
    {'att_name': 'B_19', 'att_pos': [55, 55], 'att_desc': '¿Alguna vez se ha inyectado alguna droga?'},
    {'att_name': 'C_20', 'att_pos': [56, 56], 'att_desc': 'Comunicación con los padres sobre sexualidad'},
    {'att_name': 'C_21', 'att_pos': [57, 58], 'att_desc': 'Fuente preferida de información sexual'},
    {'att_name': 'C_22', 'att_pos': [59, 60], 'att_desc': 'Fuente principal de información sexual'},
    {'att_name': 'C_23', 'att_pos': [61, 62], 'att_desc': 'Fuente de información sobre métodos anticonceptivos'},
    {'att_name': 'C_24', 'att_pos': [63, 63], 'att_desc': '¿Ha tenido relaciones sexuales?'},
    {'att_name': 'C_25', 'att_pos': [64, 64], 'att_desc': '¿Con quién (hombre/mujer) ha tenido relaciones sexuales?'},
    {'att_name': 'C1_28', 'att_pos': [65, 66], 'att_desc': 'Edad de inicio de las relaciones sexuales'},
    {'att_name': 'C1_29', 'att_pos': [67, 68], 'att_desc': 'Edad de la mujer con la que tuvo su primera relación sexual'},
    {'att_name': 'C1_30', 'att_pos': [69, 69], 'att_desc': 'Uso de preservativo en la primera relación sexual'},
    {'att_name': 'C1_31', 'att_pos': [70, 70], 'att_desc': '¿Tomaron precauciones para evitar el embarazo?'},
    {'att_name': 'C1_32A', 'att_pos': [71, 71], 'att_desc': 'Métodos anticonceptivos usados: Preservativo'},
    {'att_name': 'C1_32B', 'att_pos': [72, 72], 'att_desc': 'Métodos anticonceptivos usados: Píldora'},
    {'att_name': 'C1_32C', 'att_pos': [73, 73], 'att_desc': 'Métodos anticonceptivos usados: Marcha atrás o retirada'},
    {'att_name': 'C1_32D', 'att_pos': [74, 74], 'att_desc': 'Métodos anticonceptivos usados: Píldora del día siguiente'},
    {'att_name': 'C1_32E', 'att_pos': [75, 75], 'att_desc': 'Métodos anticonceptivos usados: “Ogino” (método del ritmo)'},
    {'att_name': 'C1_32F', 'att_pos': [76, 76], 'att_desc': 'Métodos anticonceptivos usados: Otros métodos (cremas espermicidas, diafragma, DIU, vasectomía, ligadura de trompas...)'},
    {'att_name': 'C1_32G', 'att_pos': [77, 77], 'att_desc': 'Métodos anticonceptivos usados: Nos sentíamos seguros porque fue durante la menstruación '},
    {'att_name': 'C1_32H', 'att_pos': [78, 78], 'att_desc': 'Métodos anticonceptivos usados: No consta'},
    {'att_name': 'C1_33', 'att_pos': [79, 79], 'att_desc': 'Número de parejas sexuales'},
    {'att_name': 'C1_34', 'att_pos': [80, 80], 'att_desc': 'Uso de preservativo '},
    {'att_name': 'C1_35', 'att_pos': [81, 81], 'att_desc': 'Uso de preservativo en la última relación sexual'},
    {'att_name': 'C1_36', 'att_pos': [82, 82], 'att_desc': 'Uso de prostitución alguna vez en la vida'},
    {'att_name': 'C1_37', 'att_pos': [83, 83], 'att_desc': 'Última relación con prostitución'},
    {'att_name': 'C1_38', 'att_pos': [84, 84], 'att_desc': 'Uso de preservativo en la última relación con prostitución'},
    {'att_name': 'C1_39A', 'att_pos': [85, 85], 'att_desc': '¿Ha tenido relaciones sexuales?'},
    {'att_name': 'C1_39B', 'att_pos': [86, 87], 'att_desc': 'Número de parejas sexuales'},
    {'att_name': 'C1_40', 'att_pos': [88, 88], 'att_desc': 'Uso de preservativo '},
    {'att_name': 'C1_41', 'att_pos': [89, 89], 'att_desc': 'Relaciones sexules con parejas ocasionales'},
    {'att_name': 'C1_42', 'att_pos': [90, 90], 'att_desc': 'Uso de preservativo con parejas ocasionales'},
    {'att_name': 'C1_43', 'att_pos': [91, 91], 'att_desc': '¿Ha tenido relaciones sexuales?'},
    {'att_name': 'C1_44', 'att_pos': [92, 93], 'att_desc': 'Número de días que ha tenido relaciones sexuales'},
    {'att_name': 'C1_45', 'att_pos': [94, 94], 'att_desc': '¿Ha tenido relaciones sexuales en los últimos 12 meses con nuevas parejas?'},
    {'att_name': 'C1_46A', 'att_pos': [95, 96], 'att_desc': 'Número de nuevas parejas sexuales'},
    {'att_name': 'C1_47', 'att_pos': [97, 97], 'att_desc': '¿Ha sido esta la primera vez en su vida que ha tenido relaciones sexuales (con mujeres)?'},
    {'att_name': 'C1_48', 'att_pos': [98, 99], 'att_desc': 'Edad de la pareja la primera vez que tuvieron relaciones sexuales'},
    {'att_name': 'C1_49', 'att_pos': [100, 100], 'att_desc': 'Tipo de relación con la última nueva pareja la primera vez que tuvieron relaciones sexuales'},
    {'att_name': 'C1_50', 'att_pos': [101, 101], 'att_desc': '¿Estaba bebido la primera vez que tuvieron relaciones sexuales con pareja?'},
    {'att_name': 'C1_51', 'att_pos': [102, 102], 'att_desc': 'Uso de preservativo esta primera vez'},
    {'att_name': 'C1_52', 'att_pos': [103, 103], 'att_desc': '¿Quién llevaba el preservativo?'},
    {'att_name': 'C1_53A', 'att_pos': [104, 105], 'att_desc': 'Razón por la que no usaron preservativo esta primera vez'},
    {'att_name': 'C1_53B', 'att_pos': [106, 107], 'att_desc': 'Razón por la que no usaron preservativo esta primera vez'},
    {'att_name': 'C1_54', 'att_pos': [108, 108], 'att_desc': '¿Tomaron precauciones para evitar el embarazo?'},
    {'att_name': 'C1_55A', 'att_pos': [109, 109], 'att_desc': 'Métodos anticonceptivos usados: Preservativo'},
    {'att_name': 'C1_55B', 'att_pos': [110, 110], 'att_desc': 'Métodos anticonceptivos usados: Píldora'},
    {'att_name': 'C1_55C', 'att_pos': [111, 111], 'att_desc': 'Métodos anticonceptivos usados: Marcha atrás o retirada'},
    {'att_name': 'C1_55D', 'att_pos': [112, 112], 'att_desc': 'Métodos anticonceptivos usados: Píldora del día siguiente'},
    {'att_name': 'C1_55E', 'att_pos': [113, 113], 'att_desc': 'Métodos anticonceptivos usados: “Ogino” (método del ritmo)'},
    {'att_name': 'C1_55F', 'att_pos': [114, 114], 'att_desc': 'Métodos anticonceptivos usados: Otros métodos (cremas espermicidas, diafragma, DIU, vasectomía, ligadura de trompas...)'},
    {'att_name': 'C1_55G', 'att_pos': [115, 115], 'att_desc': 'Métodos anticonceptivos usados: Nos sentíamos seguros porque fue durante la menstruación '},
    {'att_name': 'C1_55H', 'att_pos': [116, 116], 'att_desc': 'Métodos anticonceptivos usados: No consta'},
    {'att_name': 'C1_56', 'att_pos': [117, 117], 'att_desc': '¿Cree que esta pareja mantenía relaciones sexuales con otras personas?'},
    {'att_name': 'C1_57', 'att_pos': [118, 118], 'att_desc': '¿Mantenía relaciones sexuales con otras personas?'},
    {'att_name': 'C1_58', 'att_pos': [119, 119], 'att_desc': 'Después de esta primera relación sexual, ¿volvieron a mantener relaciones sexuales?'},
    {'att_name': 'C1_59', 'att_pos': [120, 120], 'att_desc': 'Uso de preservativo la última vez que tuvieron relaciones sexuales'},
    {'att_name': 'C1_60', 'att_pos': [121, 121], 'att_desc': '¿Tomaron precauciones para evitar el embarazo la última vez?'},
    {'att_name': 'C1_61A', 'att_pos': [122, 122], 'att_desc': 'Métodos anticonceptivos usados la última vez: Preservativo'},
    {'att_name': 'C1_61B', 'att_pos': [123, 123], 'att_desc': 'Métodos anticonceptivos usados la última vez: Píldora'},
    {'att_name': 'C1_61C', 'att_pos': [124, 124], 'att_desc': 'Métodos anticonceptivos usados la última vez: Marcha atrás o retirada'},
    {'att_name': 'C1_61D', 'att_pos': [125, 125], 'att_desc': 'Métodos anticonceptivos usados la última vez: Píldora del día siguiente'},
    {'att_name': 'C1_61E', 'att_pos': [126, 126], 'att_desc': 'Métodos anticonceptivos usados la última vez: “Ogino” (método del ritmo)'},
    {'att_name': 'C1_61F', 'att_pos': [127, 127], 'att_desc': 'Métodos anticonceptivos usados la última vez: Otros métodos (cremas espermicidas, diafragma, DIU, vasectomía, ligadura de trompas...)'},
    {'att_name': 'C1_61G', 'att_pos': [128, 128], 'att_desc': 'Métodos anticonceptivos usados la última vez: Nos sentíamos seguros porque fue durante la menstruación '},
    {'att_name': 'C1_61H', 'att_pos': [129, 129], 'att_desc': 'Métodos anticonceptivos usados la última vez: No consta'},
    {'att_name': 'C1_62', 'att_pos': [130, 130], 'att_desc': 'Actitud ante el uso de preservativos'},
    {'att_name': 'C2_28', 'att_pos': [131, 132], 'att_desc': 'Edad de inicio de las relaciones sexuales con un hombre'},
    {'att_name': 'C2_29', 'att_pos': [133, 134], 'att_desc': 'Edad del hombre con el que tuvo su primera relación sexual'},
    {'att_name': 'C2_30', 'att_pos': [135, 135], 'att_desc': 'Realización de penetración anal'},
    {'att_name': 'C2_31', 'att_pos': [136, 136], 'att_desc': 'Uso de preservativo'},
    {'att_name': 'C2_32', 'att_pos': [137, 137], 'att_desc': 'Número de parejas sexuales'},
    {'att_name': 'C2_33', 'att_pos': [138, 138], 'att_desc': 'Uso de preservativo '},
    {'att_name': 'C2_34', 'att_pos': [139, 139], 'att_desc': 'Uso de preservativo en la última relación sexual'},
    {'att_name': 'C2_35', 'att_pos': [140, 140], 'att_desc': 'Uso de prostitución alguna vez en la vida'},
    {'att_name': 'C2_36', 'att_pos': [141, 141], 'att_desc': 'Última relación con prostitución'},
    {'att_name': 'C2_37', 'att_pos': [142, 142], 'att_desc': 'Realización de penetración anal en esta última relación'},
    {'att_name': 'C2_38', 'att_pos': [143, 143], 'att_desc': 'Uso de preservativo en la última relación con prostitución'},
    {'att_name': 'C2_39A', 'att_pos': [144, 144], 'att_desc': '¿Ha tenido relaciones sexuales?'},
    {'att_name': 'C2_39B', 'att_pos': [145, 146], 'att_desc': 'Número de parejas sexuales'},
    {'att_name': 'C2_40', 'att_pos': [147, 147], 'att_desc': 'Uso de preservativo '},
    {'att_name': 'C2_41', 'att_pos': [148, 148], 'att_desc': 'Relaciones sexules con parejas ocasionales'},
    {'att_name': 'C2_42', 'att_pos': [149, 149], 'att_desc': 'Uso de preservativo con parejas ocasionales'},
    {'att_name': 'C2_43', 'att_pos': [150, 150], 'att_desc': '¿Ha tenido relaciones sexuales?'},
    {'att_name': 'C2_44', 'att_pos': [151, 152], 'att_desc': 'Número de días que ha tenido relaciones sexuales'},
    {'att_name': 'C2_45', 'att_pos': [153, 153], 'att_desc': '¿Ha tenido relaciones sexuales en los últimos 12 meses con nuevas parejas?'},
    {'att_name': 'C2_46A', 'att_pos': [154, 155], 'att_desc': 'Número de nuevas parejas sexuales'},
    {'att_name': 'C2_47', 'att_pos': [156, 156], 'att_desc': '¿Ha sido esta la primera vez en su vida que ha tenido relaciones sexuales con hombres?'},
    {'att_name': 'C2_48', 'att_pos': [157, 158], 'att_desc': 'Edad de la pareja la primera vez que tuvieron relaciones sexuales'},
    {'att_name': 'C2_49', 'att_pos': [159, 159], 'att_desc': 'Realización de penetración anal'},
    {'att_name': 'C2_50', 'att_pos': [160, 160], 'att_desc': 'Tipo de relación la primera vez que tuvieron relaciones sexuales'},
    {'att_name': 'C2_51', 'att_pos': [161, 161], 'att_desc': '¿Estaba bebido la primera vez que tuvieron relaciones sexuales con pareja?'},
    {'att_name': 'C2_52', 'att_pos': [162, 162], 'att_desc': 'Uso de preservativo esta primera vez'},
    {'att_name': 'C2_53A', 'att_pos': [163, 164], 'att_desc': 'Razón por la que no usaron preservativo esta primera vez'},
    {'att_name': 'C2_53B', 'att_pos': [165, 166], 'att_desc': 'Razón por la que no usaron preservativo esta primera vez'},
    {'att_name': 'C2_54', 'att_pos': [167, 167], 'att_desc': '¿Cree que esta pareja mantenía relaciones sexuales con otras personas?'},
    {'att_name': 'C2_55', 'att_pos': [168, 168], 'att_desc': '¿Mantenía relaciones sexuales con otras personas?'},
    {'att_name': 'C2_56', 'att_pos': [169, 169], 'att_desc': 'Después de esta primera relación sexual, ¿volvieron a mantener relaciones sexuales?'},
    {'att_name': 'C2_57', 'att_pos': [170, 170], 'att_desc': 'Realización de penetración anal la última vez que tuvieron relaciones sexuales'},
    {'att_name': 'C2_58', 'att_pos': [171, 171], 'att_desc': 'Uso de preservativo la última vez que tuvieron relaciones sexuales'},
    {'att_name': 'C2_59', 'att_pos': [172, 172], 'att_desc': 'Actitud ante el uso de preservativos'},
    {'att_name': 'C_26', 'att_pos': [173, 173], 'att_desc': 'Realización de prácticas sexuales con mujeres'},
    {'att_name': 'C_27', 'att_pos': [174, 174], 'att_desc': '¿Con quién (hombre/mujer) ha tenido relaciones sexuales?'},
    {'att_name': 'C3_28', 'att_pos': [175, 176], 'att_desc': 'Edad de inicio de las relaciones sexuales con una mujer'},
    {'att_name': 'C3_29', 'att_pos': [177, 178], 'att_desc': 'Edad del hombre con el que tuvo su primera relación sexual'},
    {'att_name': 'C3_30', 'att_pos': [179, 179], 'att_desc': 'Uso de preservativo en la primera relación sexual'},
    {'att_name': 'C3_31', 'att_pos': [180, 180], 'att_desc': '¿Tomaron precauciones para evitar el embarazo?'},
    {'att_name': 'C3_32A', 'att_pos': [181, 181], 'att_desc': 'Métodos anticonceptivos usados: Preservativo'},
    {'att_name': 'C3_32B', 'att_pos': [182, 182], 'att_desc': 'Métodos anticonceptivos usados: Píldora'},
    {'att_name': 'C3_32C', 'att_pos': [183, 183], 'att_desc': 'Métodos anticonceptivos usados: Marcha atrás o retirada'},
    {'att_name': 'C3_32D', 'att_pos': [184, 184], 'att_desc': 'Métodos anticonceptivos usados: Píldora del día siguiente'},
    {'att_name': 'C3_32E', 'att_pos': [185, 185], 'att_desc': 'Métodos anticonceptivos usados: “Ogino” (método del ritmo)'},
    {'att_name': 'C3_32F', 'att_pos': [186, 186], 'att_desc': 'Métodos anticonceptivos usados: Otros métodos (cremas espermicidas, diafragma, DIU, vasectomía, ligadura de trompas...)'},
    {'att_name': 'C3_32G', 'att_pos': [187, 187], 'att_desc': 'Métodos anticonceptivos usados: Nos sentíamos seguros porque fue durante la menstruación '},
    {'att_name': 'C3_32H', 'att_pos': [188, 188], 'att_desc': 'Métodos anticonceptivos usados: No consta'},
    {'att_name': 'C3_33', 'att_pos': [189, 189], 'att_desc': 'Número de parejas sexuales'},
    {'att_name': 'C3_34', 'att_pos': [190, 190], 'att_desc': 'Uso de preservativo '},
    {'att_name': 'C3_35', 'att_pos': [191, 191], 'att_desc': 'Uso de preservativo en la última relación sexual'},
    {'att_name': 'C3_36A', 'att_pos': [192, 192], 'att_desc': '¿Ha tenido relaciones sexuales?'},
    {'att_name': 'C3_36B', 'att_pos': [193, 194], 'att_desc': 'Número de parejas sexuales'},
    {'att_name': 'C3_37', 'att_pos': [195, 195], 'att_desc': 'Uso de preservativo '},
    {'att_name': 'C3_38', 'att_pos': [196, 196], 'att_desc': 'Relaciones sexules con parejas ocasionales'},
    {'att_name': 'C3_39', 'att_pos': [197, 197], 'att_desc': 'Uso de preservativo con parejas ocasionales'},
    {'att_name': 'C3_40', 'att_pos': [198, 198], 'att_desc': '¿Ha tenido relaciones sexuales?'},
    {'att_name': 'C3_41', 'att_pos': [199, 200], 'att_desc': 'Número de días que ha tenido relaciones sexuales'},
    {'att_name': 'C3_42', 'att_pos': [201, 201], 'att_desc': '¿Ha tenido relaciones sexuales en los últimos 12 meses con nuevas parejas?'},
    {'att_name': 'C3_43A', 'att_pos': [202, 203], 'att_desc': 'Número de nuevas parejas sexuales'},
    {'att_name': 'C3_44', 'att_pos': [204, 204], 'att_desc': '¿Ha sido esta la primera vez en su vida que ha tenido relaciones sexuales?'},
    {'att_name': 'C3_45', 'att_pos': [205, 206], 'att_desc': 'Edad de la pareja la primera vez que tuvieron relaciones sexuales'},
    {'att_name': 'C3_46', 'att_pos': [207, 207], 'att_desc': 'Tipo de relación la primera vez que tuvieron relaciones sexuales'},
    {'att_name': 'C3_47', 'att_pos': [208, 208], 'att_desc': '¿Estaba bebido la primera vez que tuvieron relaciones sexuales con pareja?'},
    {'att_name': 'C3_48', 'att_pos': [209, 209], 'att_desc': 'Uso de preservativo esta primera vez'},
    {'att_name': 'C3_49', 'att_pos': [210, 210], 'att_desc': '¿Quién llevaba el preservativo?'},
    {'att_name': 'C3_50A', 'att_pos': [211, 212], 'att_desc': 'Razón por la que no usaron preservativo esta primera vez'},
    {'att_name': 'C3_50B', 'att_pos': [213, 214], 'att_desc': 'Razón por la que no usaron preservativo esta primera vez'},
    {'att_name': 'C3_51', 'att_pos': [215, 215], 'att_desc': '¿Tomaron precauciones para evitar el embarazo?'},
    {'att_name': 'C3_52A', 'att_pos': [216, 216], 'att_desc': 'Métodos anticonceptivos usados: Preservativo'},
    {'att_name': 'C3_52B', 'att_pos': [217, 217], 'att_desc': 'Métodos anticonceptivos usados: Píldora'},
    {'att_name': 'C3_52C', 'att_pos': [218, 218], 'att_desc': 'Métodos anticonceptivos usados: Marcha atrás o retirada'},
    {'att_name': 'C3_52D', 'att_pos': [219, 219], 'att_desc': 'Métodos anticonceptivos usados: Píldora del día siguiente'},
    {'att_name': 'C3_52E', 'att_pos': [220, 220], 'att_desc': 'Métodos anticonceptivos usados: “Ogino” (método del ritmo)'},
    {'att_name': 'C3_52F', 'att_pos': [221, 221], 'att_desc': 'Métodos anticonceptivos usados: Otros métodos (cremas espermicidas, diafragma, DIU, vasectomía, ligadura de trompas...)'},
    {'att_name': 'C3_52G', 'att_pos': [222, 222], 'att_desc': 'Métodos anticonceptivos usados: Nos sentíamos seguros porque fue durante la menstruación '},
    {'att_name': 'C3_52H', 'att_pos': [223, 223], 'att_desc': 'Métodos anticonceptivos usados: No consta'},
    {'att_name': 'C3_53', 'att_pos': [224, 224], 'att_desc': '¿Cree que esta pareja mantenía relaciones sexuales con otras personas?'},
    {'att_name': 'C3_54', 'att_pos': [225, 225], 'att_desc': '¿Mantenía relaciones sexuales con otras personas?'},
    {'att_name': 'C3_55', 'att_pos': [226, 226], 'att_desc': 'Después de esta primera relación sexual, ¿volvieron a mantener relaciones sexuales?'},
    {'att_name': 'C3_56', 'att_pos': [227, 227], 'att_desc': 'Uso de preservativo la última vez'},
    {'att_name': 'C3_57', 'att_pos': [228, 228], 'att_desc': '¿Tomaron precauciones para evitar el embarazo la última vez?'},
    {'att_name': 'C3_58A', 'att_pos': [229, 229], 'att_desc': 'Métodos anticonceptivos usados la última vez: Preservativo'},
    {'att_name': 'C3_58B', 'att_pos': [230, 230], 'att_desc': 'Métodos anticonceptivos usados la última vez: Píldora'},
    {'att_name': 'C3_58C', 'att_pos': [231, 231], 'att_desc': 'Métodos anticonceptivos usados la última vez: Marcha atrás o retirada'},
    {'att_name': 'C3_58D', 'att_pos': [232, 232], 'att_desc': 'Métodos anticonceptivos usados la última vez: Píldora del día siguiente'},
    {'att_name': 'C3_58E', 'att_pos': [233, 233], 'att_desc': 'Métodos anticonceptivos usados la última vez: “Ogino” (método del ritmo)'},
    {'att_name': 'C3_58F', 'att_pos': [234, 234], 'att_desc': 'Métodos anticonceptivos usados la última vez: Otros métodos (cremas espermicidas, diafragma, DIU, vasectomía, ligadura de trompas...)'},
    {'att_name': 'C3_58G', 'att_pos': [235, 235], 'att_desc': 'Métodos anticonceptivos usados la última vez: Nos sentíamos seguros porque fue durante la menstruación '},
    {'att_name': 'C3_58H', 'att_pos': [236, 236], 'att_desc': 'Métodos anticonceptivos usados la última vez: No consta'},
    {'att_name': 'C3_59', 'att_pos': [237, 237], 'att_desc': 'Actitud ante el uso de preservativos'},
    {'att_name': 'D_63A', 'att_pos': [238, 238], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS: Infección por clamidia?'},
    {'att_name': 'D_63B', 'att_pos': [239, 239], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS:  Gonorrea?'},
    {'att_name': 'D_63C', 'att_pos': [240, 240], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS: Sífilis?'},
    {'att_name': 'D_63D', 'att_pos': [241, 241], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS: Tricomonas?'},
    {'att_name': 'D_63E', 'att_pos': [242, 242], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS: Herpes genital?'},
    {'att_name': 'D_63F', 'att_pos': [243, 243], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS:Úlceras genitales o condiloma?'},
    {'att_name': 'D_63G', 'att_pos': [244, 244], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS:Micosis u hongos?'},
    {'att_name': 'D_63H', 'att_pos': [245, 245], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS: Hepatitis B?'},
    {'att_name': 'D_63I', 'att_pos': [246, 246], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS:  Uretritis no específica?'},
    {'att_name': 'D_63J', 'att_pos': [247, 247], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS: Ladillas o pediculosis genital?'},
    {'att_name': 'D_63K', 'att_pos': [248, 248], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS: Otra enfermedad de transmisión sexual?'},
    {'att_name': 'D_63L', 'att_pos': [249, 249], 'att_desc': 'No me han diagnosticado ninguna ETS'},
    {'att_name': 'D_63M', 'att_pos': [250, 250], 'att_desc': '¿Le han diagnosticado alguna vez la siguiente ETS? No consta'},
    {'att_name': 'D_64', 'att_pos': [251, 252], 'att_desc': 'Última ETS diagnosticada'},
    {'att_name': 'D_65', 'att_pos': [253, 253], 'att_desc': 'Tiempo desde la última ETS'},
    {'att_name': 'E_66', 'att_pos': [254, 254], 'att_desc': 'Donación de sangre'},
    {'att_name': 'E_67', 'att_pos': [255, 255], 'att_desc': 'Prueba específica del VIH'},
    {'att_name': 'E_68', 'att_pos': [256, 256], 'att_desc': 'Tiempo que haces desde la última prueba específica del VIH'},
    {'att_name': 'E_69', 'att_pos': [257, 257], 'att_desc': 'Razón por la que se hizo la prueba'},
    {'att_name': 'E_70', 'att_pos': [258, 259], 'att_desc': 'Lugar de realización de la prueba'},
    {'att_name': 'E_71', 'att_pos': [260, 260], 'att_desc': '¿Llegó a saber los resultados de la prueba?'},
    {'att_name': 'F_72A', 'att_pos': [261, 261], 'att_desc': 'Opinión sobre el riesgo de infección del VIH según distintas prácticas '},
    {'att_name': 'F_72B', 'att_pos': [262, 262], 'att_desc': 'Opinión sobre el riesgo de infección del VIH según distintas prácticas '},
    {'att_name': 'F_72C', 'att_pos': [263, 263], 'att_desc': 'Opinión sobre el riesgo de infección del VIH según distintas prácticas '},
    {'att_name': 'F_72D', 'att_pos': [264, 264], 'att_desc': 'Opinión sobre el riesgo de infección del VIH según distintas prácticas '},
    {'att_name': 'F_72E', 'att_pos': [265, 265], 'att_desc': 'Opinión sobre el riesgo de infección del VIH según distintas prácticas '},
    {'att_name': 'F_72F', 'att_pos': [266, 266], 'att_desc': 'Opinión sobre el riesgo de infección del VIH según distintas prácticas '},
    {'att_name': 'F_72G', 'att_pos': [267, 267], 'att_desc': 'Opinión sobre el riesgo de infección del VIH según distintas prácticas '},
    {'att_name': 'F_73A', 'att_pos': [268, 268], 'att_desc': 'Identificación de los mecanismos de transmisión'},
    {'att_name': 'F_73B', 'att_pos': [269, 269], 'att_desc': 'Identificación de los mecanismos de transmisión'},
    {'att_name': 'F_73C', 'att_pos': [270, 270], 'att_desc': 'Identificación de los mecanismos de transmisión'},
    {'att_name': 'F_73D', 'att_pos': [271, 271], 'att_desc': 'Identificación de los mecanismos de transmisión'},
    {'att_name': 'F_73E', 'att_pos': [272, 272], 'att_desc': 'Identificación de los mecanismos de transmisión'},
    {'att_name': 'F_73F', 'att_pos': [273, 273], 'att_desc': 'Identificación de los mecanismos de transmisión'},
    {'att_name': 'F_73G', 'att_pos': [274, 274], 'att_desc': 'Identificación de los mecanismos de transmisión'},
    {'att_name': 'F_73H', 'att_pos': [275, 275], 'att_desc': 'Identificación de los mecanismos de transmisión'},
    {'att_name': 'F_73I', 'att_pos': [276, 276], 'att_desc': 'Identificación de los mecanismos de transmisión'},
    {'att_name': 'F_74', 'att_pos': [277, 277], 'att_desc': 'Opinión sobre el riesgo de infección d las personas que se inyectan drogas'},
    {'att_name': 'F_75', 'att_pos': [278, 278], 'att_desc': 'Percepción del riesgo propio de contraer el sida'},
    {'att_name': 'F_76', 'att_pos': [279, 279], 'att_desc': '¿Ha tenido miedo de haber contraido el sida?'},
    {'att_name': 'F_77', 'att_pos': [280, 280], 'att_desc': 'Trabajaría o estudiaría con una persona infectada con VIH'},
    {'att_name': 'F_78A', 'att_pos': [281, 281], 'att_desc': 'Eficacia de las medidas preventivas'},
    {'att_name': 'F_78B', 'att_pos': [282, 282], 'att_desc': 'Eficacia de las medidas preventivas'},
    {'att_name': 'F_78C', 'att_pos': [283, 283], 'att_desc': 'Eficacia de las medidas preventivas'},
    {'att_name': 'F_78D', 'att_pos': [284, 284], 'att_desc': 'Eficacia de las medidas preventivas'},
    {'att_name': 'F_78E', 'att_pos': [285, 285], 'att_desc': 'Eficacia de las medidas preventivas'},
    {'att_name': 'F_78F', 'att_pos': [286, 286], 'att_desc': 'Eficacia de las medidas preventivas'},
    {'att_name': 'F_78G', 'att_pos': [287, 287], 'att_desc': 'Eficacia de las medidas preventivas'},
    {'att_name': 'F_78H', 'att_pos': [288, 288], 'att_desc': 'Eficacia de las medidas preventivas'},
    {'att_name': 'F_78I', 'att_pos': [289, 289], 'att_desc': 'Eficacia de las medidas preventivas'},
    {'att_name': 'F_79A', 'att_pos': [290, 290], 'att_desc': 'Opinión acerca de los preservativos'},
    {'att_name': 'F_79B', 'att_pos': [291, 291], 'att_desc': 'Opinión acerca de los preservativos'},
    {'att_name': 'F_79C', 'att_pos': [292, 292], 'att_desc': 'Opinión acerca de los preservativos'},
    {'att_name': 'F_79D', 'att_pos': [293, 293], 'att_desc': 'Opinión acerca de los preservativos'},
    {'att_name': 'F_79E', 'att_pos': [294, 294], 'att_desc': 'Opinión acerca de los preservativos'},
    {'att_name': 'F_79F', 'att_pos': [295, 295], 'att_desc': 'Opinión acerca de los preservativos'},
    {'att_name': 'F_79G', 'att_pos': [296, 296], 'att_desc': 'Opinión acerca de los preservativos'},
    {'att_name': 'F_80', 'att_pos': [297, 297], 'att_desc': 'Creencias religiosas'},
    {'att_name': 'F_81', 'att_pos': [298, 298], 'att_desc': 'Asistencia a actos religiosos'},
    {'att_name': 'FACELE', 'att_pos': [299, 309], 'att_desc': 'Factor de elevación'},
    {'att_name': 'TAMUNI', 'att_pos': [310, 310], 'att_desc': 'Tamaño del municipio de residencia'},
    {'att_name': 'NIVELMAX', 'att_pos': [311, 311], 'att_desc': 'Nivel máximo de estudios de los padres'},
    {'att_name': 'DERIVA', 'att_pos': [312, 312], 'att_desc': 'Personas con las que ha convivido en los últimos 12 meses'},
]

filter_positions = [
    [1, 2],
    [3, 3],
    [6, 9],
    [13, 13],
    [14, 15],
    [21,22],
    [23,23],
    [35, 36],
    [38, 38],
    [42, 42],
    [310, 310],
    [312, 312]
]

filter = [
    '09', #CCAA
    '6', #SEXO
    [1957,1960], #A_2B
    '1', #A_3A
    '09', #A_3B
    '01', #A_5
    '1', #A_6_1
    '02', #A_8
    '2', #A_10
    '1', #B_12C
    '4', #TAMUNI
    '2' #DERIVA
]
f = open('found_data_verison_1_choices.csv','w')
f.write(','.join([d.get('att_name') for d in data_structure]))
f.write('\n')
for r in rows:
    item = []
    found = []
    for d in data_structure:
        item.append(r[d.get('att_pos')[0]-1:d.get('att_pos')[1]])
    for m in filter:
        found.append(False)
    for i, value in enumerate(filter_positions):
        if type(filter[i]) == list and len(filter[i]) > 1:
            for sub_value in range(filter[i][0],filter[i][1]+1):
                if str(sub_value) == r[value[0]-1:value[1]]:
                    found[i] = True
                    break
        else:
            if filter[i] == r[value[0]-1:value[1]]:
                found[i] = True
    
    if sum_found(found) == len(filter):
        f.write(','.join(item))
        f.write('\n')
f.close()

os.system("start EXCEL.EXE found_data_verison_1_choices.csv")